#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

PY="${PY:-/common/users/wq50/envs/pace/bin/python}"
DEVICE="${DEVICE:-cuda:0}"

# One example per ordered pair by default: GG1->GG2, ..., GG5->GG4, etc.
# Override SOURCE_GRADES/TARGET_GRADES to restrict the grid.
SOURCE_GRADES="${SOURCE_GRADES:-GG1,GG2,GG3,GG4,GG5}"
TARGET_GRADES="${TARGET_GRADES:-GG1,GG2,GG3,GG4,GG5}"
SLIDES_PER_PAIR="${SLIDES_PER_PAIR:-1}"
CANDIDATE_REGIONS_PER_PAIR="${CANDIDATE_REGIONS_PER_PAIR:-40}"

EDIT_POLICY="${EDIT_POLICY:-configs/edit_policies/transition_ablation/09_full_window_regen_center_preserve_outer.json}"
OUT_ROOT="${OUT_ROOT:-paper_outputs/prad_gleason_grade_to_grade_policy09_examples}"
REGION_ROOT="${REGION_ROOT:-${OUT_ROOT}/_regions}"
REFRESH_REGIONS="${REFRESH_REGIONS:-0}"
SKIP_EXISTING="${SKIP_EXISTING:-1}"
OUTPUT_MODE="${OUTPUT_MODE:-debug}"
UPDATE_PAPER_OUTPUTS="${UPDATE_PAPER_OUTPUTS:-0}"

# Leave planning/commit knobs unset so the JSON policy is the source of truth.
COMMIT_MODE="${COMMIT_MODE:-}"
COMMIT_FEATHER_PX="${COMMIT_FEATHER_PX:-}"
COMMIT_HALO_CELLS="${COMMIT_HALO_CELLS:-}"
COMMIT_HALO_ALPHA="${COMMIT_HALO_ALPHA:-}"
WINDOW_STRIDE_CELLS="${WINDOW_STRIDE_CELLS:-}"
WINDOW_SELECTION_MODE="${WINDOW_SELECTION_MODE:-}"
STEER_FULL_SUPPORT="${STEER_FULL_SUPPORT:-}"
PRESERVE_FULL_SUPPORT="${PRESERVE_FULL_SUPPORT:-}"

PY="${PY}" \
DEVICE="${DEVICE}" \
SOURCE_GRADES="${SOURCE_GRADES}" \
TARGET_GRADES="${TARGET_GRADES}" \
SLIDES_PER_PAIR="${SLIDES_PER_PAIR}" \
CANDIDATE_REGIONS_PER_PAIR="${CANDIDATE_REGIONS_PER_PAIR}" \
EDIT_POLICY="${EDIT_POLICY}" \
OUT_ROOT="${OUT_ROOT}" \
REGION_ROOT="${REGION_ROOT}" \
REFRESH_REGIONS="${REFRESH_REGIONS}" \
SKIP_EXISTING="${SKIP_EXISTING}" \
OUTPUT_MODE="${OUTPUT_MODE}" \
UPDATE_PAPER_OUTPUTS="${UPDATE_PAPER_OUTPUTS}" \
COMMIT_MODE="${COMMIT_MODE}" \
COMMIT_FEATHER_PX="${COMMIT_FEATHER_PX}" \
COMMIT_HALO_CELLS="${COMMIT_HALO_CELLS}" \
COMMIT_HALO_ALPHA="${COMMIT_HALO_ALPHA}" \
WINDOW_STRIDE_CELLS="${WINDOW_STRIDE_CELLS}" \
WINDOW_SELECTION_MODE="${WINDOW_SELECTION_MODE}" \
STEER_FULL_SUPPORT="${STEER_FULL_SUPPORT}" \
PRESERVE_FULL_SUPPORT="${PRESERVE_FULL_SUPPORT}" \
"${SCRIPT_DIR}/07_run_grade_to_grade_steering.sh"
